server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Public endpoints for User Service
        - id: user_service_public
          uri: lb://user-service
          predicates:
            - Path=/users/login,/users/register,/users/send-otp,/users/verify-otp,/users/update-password

        # Protected endpoints for User Service
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: JwtAuthenticationFilter

        # Requirements Service (protected)
        - id: requirements_service
          uri: lb://requirements-service
          predicates:
            - Path=/requirements/**
          filters:
            - name: JwtAuthenticationFilter

        # Candidates Service (protected)
        - id: candidates_service
          uri: lb://candidates-service
          predicates:
            - Path=/candidate/**
          filters:
            - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
