server:
  port:8090

spring:
  cloud:
    gateway:
      routes:
        - id: user-register-service
          uri: http://192.168.0.135:8091  #User Register Service URL
          predicates:
            - Path=/users/**          #Routes "/user/**" to UserRegister
#          filters:
#            - StripPrefix=1           #Removes "/user" before forwarding

        - id: hotlist-service
          uri: http://192.168.0.135:8092    #HotList Service URL
          predicates:
            - Path=/hotlist/**          #Routes "/hotlist/**" to HotList Service
#          filters:
#            - StripPrefix=1             #Removes "/hotlist" before forwarding

#      globalcors:
#        add-to-simple-url-handler-mapping: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG