name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Version
        id: version
        run: |
          LATEST_VERSION=$(curl -s https://hub.docker.com/v2/repositories/dataquad123/dataquad-dev-apigateway/tags/ \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V | tail -n 1)

          if [ -z "$LATEST_VERSION" ]; then
            NEW_VERSION="1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
            PATCH=$((PATCH + 1))

            if [ "$PATCH" -ge 10 ]; then
              PATCH=0
              MINOR=$((MINOR + 1))
            fi

            if [ "$MINOR" -ge 10 ]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
            fi

            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi

          echo "IMAGE_TAG=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build Docker Image (no cache, no BuildKit)
        env:
          DOCKER_BUILDKIT: 0
        run: |
          set -x
          docker build --no-cache --pull -t dataquad123/dataquad-dev-apigateway:${{ env.IMAGE_TAG }} .
          docker tag dataquad123/dataquad-dev-apigateway:${{ env.IMAGE_TAG }} dataquad123/dataquad-dev-apigateway:latest

      - name: Push Docker Image with Retry
        run: |
          for i in {1..3}; do
            docker push dataquad123/dataquad-dev-apigateway:${{ env.IMAGE_TAG }} && break || sleep 10
          done

          for i in {1..3}; do
            docker push dataquad123/dataquad-dev-apigateway:latest && break || sleep 10
          done

      - name: Delete Old Images (Keep Only Last 10)
        run: |
          TAGS_TO_DELETE=$(curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} \
            "https://hub.docker.com/v2/repositories/dataquad123/dataquad-dev-apigateway/tags/?page_size=100" \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V | head -n -10)

          for TAG in $TAGS_TO_DELETE; do
            echo "Deleting tag: $TAG"
            curl -X DELETE -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} \
              "https://hub.docker.com/v2/repositories/dataquad123/dataquad-dev-apigateway/tags/$TAG/"
            sleep 1
          done
